### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by InjectedPie** [BiomeBundle/BiomeBundle#134]
using Paper 1391; Multiverse-Core v2.6.0-SNAPSHOT-b737, OpenTerrainGenerator-1.12.2-v6

	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Paper-1391]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[spigot.jar:git-Paper-1391]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[spigot.jar:git-Paper-1391]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648) [spigot.jar:git-Paper-1391]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:465) [spigot.jar:git-Paper-1391]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:428) [spigot.jar:git-Paper-1391]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [spigot.jar:git-Paper-1391]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [spigot.jar:git-Paper-1391]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at com.pg85.otg.bukkit.OTGBiomeBase.createInstance(OTGBiomeBase.java:131) ~[?:?]
	at com.pg85.otg.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:171) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:1646) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.indexSettings(ServerConfigProvider.java:264) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:135) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:79) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:68) ~[?:?]
	at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:137) ~[?:?]
	at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:311) ~[spigot.jar:git-Paper-1391]
	at org.bukkit.WorldCreator.generator(WorldCreator.java:183) ~[spigot.jar:git-Paper-1391]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:240) ~[?:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Paper-1391]
	... 8 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)
	at com.pg85.otg.bukkit.util.EnumHelper.<clinit>(EnumHelper.java:39) ~[?:?]
	at com.pg85.otg.bukkit.OTGBiomeBase.createInstance(OTGBiomeBase.java:131) ~[?:?]
	at com.pg85.otg.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:171) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:1646) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.indexSettings(ServerConfigProvider.java:264) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:135) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:79) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:68) ~[?:?]
	at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:137) ~[?:?]
	at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:311) ~[spigot.jar:git-Paper-1391]
	at org.bukkit.WorldCreator.generator(WorldCreator.java:183) ~[spigot.jar:git-Paper-1391]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:240) ~[?:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Paper-1391]
	... 8 more
Caused by: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)
	at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:?]
	at com.pg85.otg.bukkit.util.EnumHelper.<clinit>(EnumHelper.java:33) ~[?:?]
	at com.pg85.otg.bukkit.OTGBiomeBase.createInstance(OTGBiomeBase.java:131) ~[?:?]
	at com.pg85.otg.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:171) ~[?:?]
	at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:1646) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.indexSettings(ServerConfigProvider.java:264) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:135) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:79) ~[?:?]
	at com.pg85.otg.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:68) ~[?:?]
	at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:137) ~[?:?]
	at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:311) ~[spigot.jar:git-Paper-1391]
	at org.bukkit.WorldCreator.generator(WorldCreator.java:183) ~[spigot.jar:git-Paper-1391]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:240) ~[?:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Paper-1391]
	... 8 more

**Comment by MCPitman** [comment]
Paper Spigot is not supported by OTG, if it doesn't work use normal Spigot.

**Comment by InjectedPie** [comment]
ok
