### ISSUE TITLE
Error on world creation using Biome Bundle

### ISSUE THREAD

**Issue by TheSkadoosh** [BiomeBundle/BiomeBundle#168]
This was working fine a few days ago and now I git this error on world creation. It only seems to happen if I do the Biome Bundle option on creation. I do also have JustEnoughIDs installed to prevent lack of Biome ID's 

https://paste.dimdev.org/lemigukigi.mccrash

Description: Exception in server tick loop

java.lang.RuntimeException: Biome could not be registered, no free biome id's!
    at com.pg85.otg.network.ServerConfigProvider.indexSettings(ServerConfigProvider.java:484)
    at com.pg85.otg.network.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:208)
    at com.pg85.otg.network.ServerConfigProvider.loadSettings(ServerConfigProvider.java:134)
    at com.pg85.otg.network.ServerConfigProvider.<init>(ServerConfigProvider.java:74)
    at com.pg85.otg.forge.world.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:362)
    at com.pg85.otg.forge.world.OTGWorldType.getBiomeProvider(OTGWorldType.java:146)
    at net.minecraft.world.WorldProvider.init(WorldProvider.java:58)
    at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:40)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:121)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:156)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:745)

**Comment by BiomeBundle** [comment]
you ran out of biome IDs, reduce the number of biome mods

JustEnoughIDs doesn't work with OTG
