### ISSUE TITLE
Server Crash Level type

### ISSUE THREAD

**Issue by BasicallyLuci** [BiomeBundle/BiomeBundle#185]
whenever i change the level TYPE in my server to OTG
and changing the level NAME to Biome Bundle

the server does not launch at all, it crashes trying to launch

**Comment by InsideIntel** [comment]
Mine's the same, here's crash logs:

    at com.pg85.otg.configuration.biome.BiomeGroup.processBiomeData(BiomeGroup.java:106)
    at com.pg85.otg.configuration.biome.BiomeGroupManager.processBiomeData(BiomeGroupManager.java:176)
    at com.pg85.otg.network.ServerConfigProvider.loadSettings(ServerConfigProvider.java:138)
    at com.pg85.otg.network.ServerConfigProvider.<init>(ServerConfigProvider.java:74)
    at com.pg85.otg.forge.world.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:362)
    at com.pg85.otg.forge.world.OTGWorldType.getBiomeProvider(OTGWorldType.java:146)
    at net.minecraft.world.WorldProvider.init(WorldProvider.java:58)
    at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:40)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
    at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:298)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
