### ISSUE TITLE
Nether causing crashes

### ISSUE THREAD

**Issue by alexJGOD** [BiomeBundle/BiomeBundle#24]
My friend owns a survival server with the BiomeBundle mod installed. Everything works fine in the overworld and even when we travel to the nether. Although, when we travel back from the nether the server crashes within seconds of us being back on the overworld. I wasn't sure whether it was the server or the mod so I tested in singleplayer and the same error occured. My game crashes and I receive this message (I am using Optifine as well as the BiomeBundle mod):

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 9/01/17 2:27 PM
Description: Exception preparing structure feature

java.lang.NullPointerException: Exception preparing structure feature
	at com.khorn.terraincontrol.forge.generator.structure.MineshaftGen.func_75047_a(MineshaftGen.java:24)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:37)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:27)
	at com.khorn.terraincontrol.forge.ForgeWorld.prepareDefaultStructures(ForgeWorld.java:198)
	at com.khorn.terraincontrol.generator.ChunkProviderTC.generate(ChunkProviderTC.java:141)
	at com.khorn.terraincontrol.forge.generator.ChunkProvider.func_185932_a(ChunkProvider.java:58)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:842)
	at net.minecraft.block.BlockLiquid.func_176365_e(SourceFile:288)
	at net.minecraft.block.BlockStaticLiquid.func_189540_a(BlockStaticLiquid.java:26)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:474)
	at net.minecraft.world.World.func_180496_d(World.java:519)
	at net.minecraft.world.World.func_175685_c(World.java:470)
	at net.minecraft.world.World.func_175722_b(World.java:423)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368)
	at net.minecraft.world.World.func_180501_a(World.java:349)
	at net.minecraft.world.World.func_175656_a(World.java:408)
	at net.minecraft.block.BlockLiquid.func_176365_e(SourceFile:296)
	at net.minecraft.block.BlockLiquid.func_189540_a(SourceFile:281)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:474)
	at net.minecraft.world.World.func_180496_d(World.java:519)
	at net.minecraft.world.World.func_175685_c(World.java:467)
	at net.minecraft.world.World.func_175722_b(World.java:423)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368)
	at net.minecraft.world.World.func_180501_a(World.java:349)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:174)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:152)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:744)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.khorn.terraincontrol.forge.generator.structure.MineshaftGen.func_75047_a(MineshaftGen.java:24)

-- Feature being prepared --
Details:
	Is feature chunk: ~~ERROR~~ NullPointerException: null
	Chunk location: -61,30
	Chunk pos hash: 133143986115
	Structure type: com.khorn.terraincontrol.forge.generator.structure.MineshaftGen
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:37)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:27)
	at com.khorn.terraincontrol.forge.ForgeWorld.prepareDefaultStructures(ForgeWorld.java:198)
	at com.khorn.terraincontrol.generator.ChunkProviderTC.generate(ChunkProviderTC.java:141)
	at com.khorn.terraincontrol.forge.generator.ChunkProvider.func_185932_a(ChunkProvider.java:58)

-- Chunk to be generated --
Details:
	Location: -53,38
	Position hash: 167503724491
	Generator: com.khorn.terraincontrol.forge.generator.ChunkProvider@65c9cfd6
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:842)
	at net.minecraft.block.BlockLiquid.func_176365_e(SourceFile:288)
	at net.minecraft.block.BlockStaticLiquid.func_189540_a(BlockStaticLiquid.java:26)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:474)

-- Block being updated --
Details:
	Source block type: ID #10 (tile.lava // net.minecraft.block.BlockDynamicLiquid)
	Block: minecraft:lava[level=0]
	Block location: World: (-834,10,607), Chunk: (at 14,0,15 in -53,37; contains blocks -848,0,592 to -833,255,607), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_180496_d(World.java:519)
	at net.minecraft.world.World.func_175685_c(World.java:470)
	at net.minecraft.world.World.func_175722_b(World.java:423)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368)
	at net.minecraft.world.World.func_180501_a(World.java:349)
	at net.minecraft.world.World.func_175656_a(World.java:408)
	at net.minecraft.block.BlockLiquid.func_176365_e(SourceFile:296)
	at net.minecraft.block.BlockLiquid.func_189540_a(SourceFile:281)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:474)

-- Block being updated --
Details:
	Source block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Block: minecraft:flowing_lava[level=0]
	Block location: World: (-834,10,606), Chunk: (at 14,0,14 in -53,37; contains blocks -848,0,592 to -833,255,607), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_180496_d(World.java:519)
	at net.minecraft.world.World.func_175685_c(World.java:467)
	at net.minecraft.world.World.func_175722_b(World.java:423)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368)
	at net.minecraft.world.World.func_180501_a(World.java:349)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:174)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:152)

-- Block being ticked --
Details:
	Block: minecraft:flowing_water[level=6]
	Block location: World: (-833,11,606), Chunk: (at 15,0,14 in -53,37; contains blocks -848,0,592 to -833,255,607), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:744)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['alexJ_'/112, l='world', x=-830.71, y=54.00, z=374.80]]
	Chunk stats: ServerChunkCache: 786 Drop: 0
	Level seed: 8560230915395725769
	Level generator: ID 06 - TerrainControl, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-442,52,562), Chunk: (at 6,3,2 in -28,35; contains blocks -448,0,560 to -433,255,575), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 4834 game time, 4834 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 77361 (now: false), thunder time: 153394 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 56450152 bytes (53 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2202 Optifine OptiFine_1.10.2_HD_U_D4 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2202.jar) 
	UCHIJAAAA	Forge{12.18.3.2202} [Minecraft Forge] (forge-1.10.2-12.18.3.2202.jar) 
	UCHIJAAAA	terraincontrol{2.8.2-SNAPSHOT} [TerrainControl] (terraincontrol-forge-2.8.2-1.10.2-B1.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['alexJ_'/112, l='world', x=-830.71, y=54.00, z=374.80]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SM Shaders v2.1 Standard.zip
	OpenGlVersion: 4.5.0 NVIDIA 358.50
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by BiomeBundle** [comment]
There is a temporary fix for this in the latest release, it won't break your world seed.
