### ISSUE TITLE
Crash in rare structure gen

### ISSUE THREAD

**Issue by BlueEyes9** [BiomeBundle/BiomeBundle#39]
Crash when exploring.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.3.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.1.105-universal.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 1/23/17 9:43 AM
Description: Exception preparing structure feature

java.lang.NullPointerException: Exception preparing structure feature
	at com.khorn.terraincontrol.forge.generator.structure.RareBuildingStart.<init>(RareBuildingStart.java:18)
	at com.khorn.terraincontrol.forge.generator.structure.RareBuildingGen.func_75049_b(RareBuildingGen.java:102)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:39)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:27)
	at com.khorn.terraincontrol.forge.ForgeWorld.prepareDefaultStructures(ForgeWorld.java:202)
	at com.khorn.terraincontrol.generator.ChunkProviderTC.generate(ChunkProviderTC.java:141)
	at com.khorn.terraincontrol.forge.generator.ChunkProvider.func_185932_a(ChunkProvider.java:58)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_175672_r(World.java:1612)
	at drzhark.customspawner.CustomSpawner.performWorldGenSpawning(CustomSpawner.java:701)
	at drzhark.customspawner.EventHooks.peformCustomWorldGenSpawning(EventHooks.java:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_43_EventHooks_peformCustomWorldGenSpawning_Populate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.terraingen.TerrainGen.populate(TerrainGen.java:54)
	at com.khorn.terraincontrol.forge.events.TCToForgeEventConverter.onResourceProcess(TCToForgeEventConverter.java:66)
	at com.khorn.terraincontrol.TerrainControlEngine.fireResourceProcessEvent(TerrainControlEngine.java:106)
	at com.khorn.terraincontrol.TerrainControl.fireResourceProcessEvent(TerrainControl.java:80)
	at com.khorn.terraincontrol.generator.resource.Resource.process(Resource.java:146)
	at com.khorn.terraincontrol.generator.ObjectSpawner.populate(ObjectSpawner.java:70)
	at com.khorn.terraincontrol.forge.generator.ChunkProvider.func_185931_b(ChunkProvider.java:92)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.khorn.terraincontrol.forge.generator.structure.RareBuildingStart.<init>(RareBuildingStart.java:18)
	at com.khorn.terraincontrol.forge.generator.structure.RareBuildingGen.func_75049_b(RareBuildingGen.java:102)

-- Feature being prepared --
Details:
	Is feature chunk: True
	Chunk location: 3036,4381
	Chunk pos hash: 18816251726812
	Structure type: com.khorn.terraincontrol.forge.generator.structure.RareBuildingGen
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:39)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:27)
	at com.khorn.terraincontrol.forge.ForgeWorld.prepareDefaultStructures(ForgeWorld.java:202)
	at com.khorn.terraincontrol.generator.ChunkProviderTC.generate(ChunkProviderTC.java:141)
	at com.khorn.terraincontrol.forge.generator.ChunkProvider.func_185932_a(ChunkProvider.java:58)

-- Chunk to be generated --
Details:
	Location: 3041,4385
	Position hash: 18833431596001
	Generator: com.khorn.terraincontrol.forge.generator.ChunkProvider@6981dc
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_175672_r(World.java:1612)
	at drzhark.customspawner.CustomSpawner.performWorldGenSpawning(CustomSpawner.java:701)
	at drzhark.customspawner.EventHooks.peformCustomWorldGenSpawning(EventHooks.java:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_43_EventHooks_peformCustomWorldGenSpawning_Populate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.terraingen.TerrainGen.populate(TerrainGen.java:54)
	at com.khorn.terraincontrol.forge.events.TCToForgeEventConverter.onResourceProcess(TCToForgeEventConverter.java:66)
	at com.khorn.terraincontrol.TerrainControlEngine.fireResourceProcessEvent(TerrainControlEngine.java:106)
	at com.khorn.terraincontrol.TerrainControl.fireResourceProcessEvent(TerrainControl.java:80)
	at com.khorn.terraincontrol.generator.resource.Resource.process(Resource.java:146)
	at com.khorn.terraincontrol.generator.ObjectSpawner.populate(ObjectSpawner.java:70)
	at com.khorn.terraincontrol.forge.generator.ChunkProvider.func_185931_b(ChunkProvider.java:92)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['RogueOfAmegakure'/5270, l='world', x=3190.38, y=40.00, z=4240.25], EntityPlayerMP['OzzyMandice'/5344, l='world', x=3129.95, y=68.00, z=3894.86]]
	Chunk stats: ServerChunkCache: 1017 Drop: 0
	Level seed: 811170692
	Level generator: ID 06 - TerrainControl, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (3314,56,4025), Chunk: (at 2,3,9 in 207,251; contains blocks 3312,0,4016 to 3327,255,4031), Region: (6,7; contains chunks 192,224 to 223,255, blocks 3072,0,3584 to 3583,255,4095)
	Level time: 260617 game time, 260617 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 9247 (now: false), thunder time: 12138 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1028160712 bytes (980 MB) / 4235198464 bytes (4039 MB) up to 4235198464 bytes (4039 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2221 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2221.jar) 
	UCHIJAAAA	Forge{12.18.3.2221} [Minecraft Forge] (forge-1.10.2-12.18.3.2221.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.2.198-universal.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
	UCHIJAAAA	betterfoliage{2.1.3} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.3.jar) 
	UCHIJAAAA	birdsnests{1.4} [Bird's Nests] (BirdsNests1.10-1.4.jar) 
	UCHIJAAAA	cavern{1.5.5} [Cavern] (Cavern_1.10.2-v1.5.5.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.2.198} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.2.198-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCHIJAAAA	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCHIJAAAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(20nov16).jar) 
	UCHIJAAAA	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod-10.0.6.jar) 
	UCHIJAAAA	EnderStorage{2.2.0.96} [EnderStorage] (EnderStorage-1.10.2-2.2.0.96-universal.jar) 
	UCHIJAAAA	fakename{1.0} [Fake Name] (Fakename MC1.10.2 v1.0.jar) 
	UCHIJAAAA	JEI{3.14.2.398} [Just Enough Items] (jei_1.10.2-3.14.2.398.jar) 
	UCHIJAAAA	forestry{5.2.17.355} [Forestry] (forestry_1.10.2-5.2.17.355.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.2} [JourneyMap] (journeymap-1.10.2-5.4.2.jar) 
	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAA	krikkemod{1.0.3} [Krikke's Mod] (krikkemod-1.0.3.jar) 
	UCHIJAAAA	lycanitesmobs{1.15.1.5 - MC 1.10.2} [Lycanites Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	arcticmobs{1.15.1.5 - MC 1.10.2} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	demonmobs{1.15.1.5 - MC 1.10.2} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	desertmobs{1.15.1.5 - MC 1.10.2} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	forestmobs{1.15.1.5 - MC 1.10.2} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	freshwatermobs{1.15.1.5 - MC 1.10.2} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	infernomobs{1.15.1.5 - MC 1.10.2} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	junglemobs{1.15.1.5 - MC 1.10.2} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	mountainmobs{1.15.1.5 - MC 1.10.2} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	plainsmobs{1.15.1.5 - MC 1.10.2} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	saltwatermobs{1.15.1.5 - MC 1.10.2} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	shadowmobs{1.15.1.5 - MC 1.10.2} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	swampmobs{1.15.1.5 - MC 1.10.2} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJAAAA	morebees{1.10.2-1.2} [More Bees] (morebees-1.10.2-1.2 (1).jar) 
	UCHIJAAAA	moreplayermodels{1.10.2} [MorePlayerModels] (MorePlayerModels_1.10.2(11nov16).jar) 
	UCHIJAAAA	natura{1.10.2-4.1.0.17} [Natura] (natura-1.10.2-4.1.0.17.jar) 
	UCHIJAAAA	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass-1.10.2-1.3.0.jar) 
	UCHIJAAAA	reborncore{2.13.1.105} [RebornCore] (RebornCore-1.10.2-2.13.1.105-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.1.105} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.1.105-universal.jar) 
	UCHIJAAAA	Roguelike{1.5.5} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.5 (1).jar) 
	UCHIJAAAA	shetiphiancore{3.3.6} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.6.jar) 
	UCHIJAAAA	soulshardstow{1.10.2-2.6.7-48} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.7-48.jar) 
	UCHIJAAAA	tammodized{0.2.4} [TamModized] (TamModized-1.10.2-0.2.4.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJAAAA	techreborn{2.1.1.156} [TechReborn] (TechReborn-1.10.2-2.1.1.156-universal.jar) 
	UCHIJAAAA	terraincontrol{2.8.2-SNAPSHOT} [TerrainControl] (terraincontrol-forge-2.8.2-1.10.2-B1.jar) 
	UCHIJAAAA	terraqueous{1.2.16} [Terraqueous] (terraqueous-1.10.0-1.2.16.jar) 
	UCHIJAAAA	torohealthmod{1.10.2-7} [ToroHealth Damage Indicators] (torohealth-1.10.2-7.jar) 
	UCHIJAAAA	tumbleweed{1.10-0.3.1} [Tumbleweed] (tumbleweed-1.10-0.3.1.jar) 
	UCHIJAAAA	voidcraft{0.9.13} [VoidCraft] (VoidCraft-1.10.2-0.9.13.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.BlockStateLoaderTransformer
RebornCoreASM (RebornCore-1.10.2-2.13.1.105-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  shetiphian.core.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  appeng.coremod.transformer.ASMIntegration
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv4-alpha-11 for Forge 12.18.3.2185
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	AE2 Integration: IC2:OFF, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF
	Profiler Position: N/A (disabled)
	Player Count: 2 / 8; [EntityPlayerMP['RogueOfAmegakure'/5270, l='world', x=3190.38, y=40.00, z=4240.25], EntityPlayerMP['OzzyMandice'/5344, l='world', x=3129.95, y=68.00, z=3894.86]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Neeley-Justen** [comment]
Conflict with Mo'creatures.  TC and mo creatures are fighting over their spawner generation.  Not a collaborator ( and a terrible coder) or I would help.

**Comment by BiomeBundle** [comment]
A new version of Biome Bundle can be downloaded from Curse ([Forge](https://minecraft.curseforge.com/projects/biome-bundle)) or Github ([Bukkit](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0)). I expect this version to fix the issue you are experiencing, a brief changelog can be found [here](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0).

Biome Bundle is now dependant on [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator) and the installation process has changed; head over to the [installation instructions](https://github.com/BiomeBundle/BiomeBundle/wiki/Installation-Instructions) that detail how to install Biome Bundle.

Please bear in mind you will need to generate a new world with the latest update as it is not compatible with old worlds. 

Happy Exploring! ☻
