### ISSUE TITLE
New Launcher Crash

### ISSUE THREAD

**Issue by Bestfreestylist** [BiomeBundle/BiomeBundle#46]
The new launcher mojang made for operating system windows 10
this is for pc minecraft, when loading the game it gets to 5 of 7 loaded and crashes and wont give me the crash report.  
does anyone else have this issue? is there a fix?
---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/5/17 7:27 PM
Description: Exception preparing structure feature

java.lang.NullPointerException: Exception preparing structure feature
	at com.khorn.terraincontrol.forge.generator.structure.MineshaftGen.func_75047_a(MineshaftGen.java:24)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:37)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:27)
	at com.khorn.terraincontrol.forge.ForgeWorld.prepareDefaultStructures(ForgeWorld.java:198)
	at com.khorn.terraincontrol.generator.ChunkProviderTC.generate(ChunkProviderTC.java:141)
	at com.khorn.terraincontrol.forge.generator.ChunkProvider.func_185932_a(ChunkProvider.java:58)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.khorn.terraincontrol.forge.generator.structure.MineshaftGen.func_75047_a(MineshaftGen.java:24)

-- Feature being prepared --
Details:
	Is feature chunk: ~~ERROR~~ NullPointerException: null
	Chunk location: -29,187
	Chunk pos hash: 807453851619
	Structure type: com.khorn.terraincontrol.forge.generator.structure.MineshaftGen
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:37)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:27)
	at com.khorn.terraincontrol.forge.ForgeWorld.prepareDefaultStructures(ForgeWorld.java:198)
	at com.khorn.terraincontrol.generator.ChunkProviderTC.generate(ChunkProviderTC.java:141)
	at com.khorn.terraincontrol.forge.generator.ChunkProvider.func_185932_a(ChunkProvider.java:58)

-- Chunk to be generated --
Details:
	Location: -21,195
	Position hash: 841813589995
	Generator: com.khorn.terraincontrol.forge.generator.ChunkProvider@731ca329
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
	Level name: World
	All players: 1 total; [EntityPlayerMP['DerpyDubStepGuy'/200, l='World', x=-297.30, y=83.00, z=2897.57]]
	Chunk stats: ServerChunkCache: 1152 Drop: 0
	Level seed: -1177202215601435632
	Level generator: ID 06 - TerrainControl, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (43,52,66), Chunk: (at 11,3,2 in 2,4; contains blocks 32,0,64 to 47,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11568 game time, 11568 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 51071 (now: false), thunder time: 22087 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 621475432 bytes (592 MB) / 2233204736 bytes (2129 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 7, tcache: 102, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2202 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2202.jar) 
	UCHIJAAAA	Forge{12.18.3.2202} [Minecraft Forge] (forge-1.10.2-12.18.3.2202.jar) 
	UCHIJAAAA	terraincontrol{2.8.2-SNAPSHOT} [TerrainControl] (terraincontrol-forge-2.8.2-1.10.2-B1.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['DerpyDubStepGuy'/200, l='World', x=-297.30, y=83.00, z=2897.57]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by BiomeBundle** [comment]
Mineshaft issues now fixed in latest update; 

A new version of Biome Bundle can be downloaded from Curse ([Forge](https://minecraft.curseforge.com/projects/biome-bundle)) or Github ([Bukkit](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0)). I expect this version to fix the issue you are experiencing, a brief changelog can be found [here](https://github.com/BiomeBundle/BiomeBundle/releases/tag/Bukkit5.0).

Biome Bundle is now dependant on [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator) and the installation process has changed; head over to the [installation instructions](https://github.com/BiomeBundle/BiomeBundle/wiki/Installation-Instructions) that detail how to install Biome Bundle.

Please bear in mind you will need to generate a new world with the latest update as it is not compatible with old worlds. 

Happy Exploring! ☻
