### ISSUE TITLE
TC not loading - guessing its a version mismatch?

### ISSUE THREAD

**Issue by amsedal** [BiomeBundle/BiomeBundle#48]
[23:35:19] [Server thread/INFO]: [TerrainControl] Loading TerrainControl v2.8.2-SNAPSHOT
[23:35:19] [Server thread/INFO]: [TerrainControl] Enabling TerrainControl v2.8.2-SNAPSHOT
[23:35:19] [Server thread/INFO]: [TerrainControl] 22 Global custom objects loaded
[23:35:19] [Server thread/ERROR]: Error occurred while enabling TerrainControl v2.8.2-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_10_R1/WorldGenFactory
	at com.khorn.terraincontrol.bukkit.TCPlugin.onEnable(TCPlugin.java:86) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.WorldGenFactory
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	... 9 more
[23:35:19] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[23:35:19] [Server thread/INFO]: Preparing level "world"
[23:35:19] [Server thread/INFO]: [TerrainControl] Starting to enable world ''world''...
[23:35:19] [Server thread/ERROR]: [TerrainControl] Could not set generator for default world 'world': Plugin 'TerrainControl v2.8.2-SNAPSHOT
java.lang.NoClassDefFoundError: net/minecraft/server/v1_10_R1/WorldProvider
	at com.khorn.terraincontrol.bukkit.TCPlugin.getDefaultWorldGenerator(TCPlugin.java:134) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.getGenerator(CraftServer.java:1236) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:259) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.WorldProvider
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	... 6 more
[23:35:19] [Server thread/INFO]: -------- World Settings For [world] --------

**Comment by amsedal** [comment]
found the problem:

You need to use terrain control built for 1.11 not 1.10, the link can be found here:
http://forum.mctcp.com/t/terraincontrol-for-spigot-1-11/1324?source_topic_id=1692

Thank you basicmark from the mctcp forums!
