### ISSUE TITLE
Need some help here

### ISSUE THREAD

**Issue by PSILONCRAFT** [BiomeBundle/BiomeBundle#58]
[crash-2017-04-24_20.16.00-server.txt](https://github.com/BiomeBundle/BiomeBundle/files/952721/crash-2017-04-24_20.16.00-server.txt)

**Comment by PSILONCRAFT** [comment]
also got this error when pregen the world

// Who set us up the TNT?

Time: 4/25/17 11:27 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraftforge.common.BiomeDictionary.containsType(BiomeDictionary.java:440)
	at net.minecraftforge.common.BiomeDictionary.isBiomeOfType(BiomeDictionary.java:261)
	at greymerk.roguelike.dungeon.Dungeon.validLocation(Dungeon.java:217)
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:100)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:191)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at com.gecgooden.chunkgen.util.Utilities.generateChunk(Utilities.java:67)
	at com.gecgooden.chunkgen.handlers.TickHandler.onServerTick(TickHandler.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_261_TickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by MCPitman** [comment]
Fixed in OTG v17
https://minecraft.curseforge.com/projects/open-terrain-generator/files/2413721
