### ISSUE TITLE
Issue while generating new world with TerrainControl, Multiverse and BiomeBundle

### ISSUE THREAD

**Issue by WyRe** [BiomeBundle/BiomeBundle#64]
I'm having got this issue with the default config in `WorldConfig.ini` generating a new world

```
[23:33:50 INFO]: [TerrainControl] 2138 world custom objects loaded.
[23:33:51 WARN]: Unexpected exception while parsing console command "mv create real2 NORMAL -g TerrainControl"
org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.5-b719
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [spigot.1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [spigot.1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.AssertionError: Biome ID #158 returns custom biome #405 instead of its own.
        at com.khorn.terraincontrol.bukkit.TXBiomeBase.checkRegistry(TXBiomeBase.java:153) ~[?:?]
        at com.khorn.terraincontrol.bukkit.TXBiomeBase.createInstance(TXBiomeBase.java:141) ~[?:?]
        at com.khorn.terraincontrol.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43) ~[?:?]
        at com.khorn.terraincontrol.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:87) ~[?:?]
        at com.khorn.terraincontrol.configuration.ServerConfigProvider.indexSettings(ServerConfigProvider.java:288) ~[?:?]
        at com.khorn.terraincontrol.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:162) ~[?:?]
        at com.khorn.terraincontrol.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:91) ~[?:?]
        at com.khorn.terraincontrol.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:78) ~[?:?]
        at com.khorn.terraincontrol.bukkit.TXPlugin.getDefaultWorldGenerator(TXPlugin.java:138) ~[?:?]
        at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:311) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
        at org.bukkit.WorldCreator.generator(WorldCreator.java:183) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
        at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:240) ~[?:?]
        at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.1.11.2.jar:git-Spigot-3fb9445-fbb47e8]
        ... 8 more

```

What do you think? Thank you so much and sorry if it's duplicated.

**Comment by WyRe** [comment]
Feedback in here 

http://forum.mctcp.com/t/java-exception-while-generating/1743

solution to generate multiple words?

**Comment by LordSmellyPants** [comment]
Discussion continued in thread:

http://forum.mctcp.com/t/java-exception-while-generating/1743
