### ISSUE TITLE
[1.11.2] [Forge] Minecraft hangs on creation of a 'biome bundle' world

### ISSUE THREAD

**Issue by Royal-Jelly** [BiomeBundle/BiomeBundle#70]
Here is a small snip-pit from my MultiMC Log:
[20:20:49] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
at com.khorn.terraincontrol.forge.TXDimensionManager.RemoveTCDims(TXDimensionManager.java:523) ~[TXDimensionManager.class:?]
at com.khorn.terraincontrol.forge.ForgeWorld.(ForgeWorld.java:155) ~[ForgeWorld.class:?]
at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:284) ~[WorldLoader.class:?]
at com.khorn.terraincontrol.forge.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:262) ~[WorldLoader.class:?]
at com.khorn.terraincontrol.forge.TXWorldType.getBiomeProvider(TXWorldType.java:67) ~[TXWorldType.class:?]
at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:58) ~[avf.class:?]
at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40) ~[avf.class:?]
at net.minecraft.world.WorldServer.(WorldServer.java:112) ~[lw.class:?]
at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:85) ~[cch.class:?]
at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120) ~[cch.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[20:20:49] [Server thread/ERROR]: This crash report has been saved to: /home/royal-jelly/Desktop/Games/MultiMC[0.5.1]/instances/Forged with Maids [1.11.2]/minecraft/crash-reports/crash-2017-06-07_20.20.49-server.txt

And the whole log can be found here : https://paste.ee/p/OoHka

**Comment by Royal-Jelly** [comment]
This is probably not on you to fix but i thought maybe i should post a report here as well

**Comment by MCPitman** [comment]
Uh, there is no biome bundle for 1.11 yet. Looks like you compiled an
unreleased build of 1.11.2 OTG which is not something we need bug reports
on until it is released.

**Comment by Royal-Jelly** [comment]
Yeah this is true, i did compile it and i did just assume it would world across the two versions perhaps i was just being dumb

Sorry for the useless bug report ~

**Comment by MCPitman** [comment]
New OTG and BBundle for 1.11.2 is now up.
